### PR TITLE
Modifications for issue 1 - 4 

### PR DESCRIPTION
**Pull request by prernarana**
Modifications for the following enhancements 

1) Ping 6 support added.
User can pass through request whether to run Ping command or ping 6 command.

Request will now be like 

```
[{query: 'www.somesite.com', 'timeout': 1,'retry': 3,'version':"v4"},
{query: 'www.somesite.com', 'timeout': 1,'retry': 3,'version':"v6"}]
```
version parameter will now suggest Ping or Ping6 command.

2) Support for additional parameters

Plugin supports extra response parameters like max rtt,min rtt, packet Transmitted, packet Received and packet Loss.

3) Configurable timeout and retry .

Plugin supports configurable  retry (-c ) and timeout ( -W ) option in ping or ping6 commands

Request will now be like 

```
[{query: 'www.somesite.com', 'timeout': 1,'retry': 3,'version':"v4"},
{query: 'www.somesite.com', 'timeout': 1,'retry': 3,'version':"v6"}]
```

4) Change in response structure:

Response will now contain the request parameters. It will be helpful in applications where we store data in DB and analyse it later, analyzing will be easy if we have the exact request also.

Response will be like 

```
[{
 	"response": {
 		"status": "success",
 		"result": {
 			"target": "www.somesite.com",
 			"avgRtt": "4.476",
 			"maxRtt": "6.348",
 			"minRtt": "1.007",
 			"pctTransmitted": "3",
 			"pctReceived": "3",
 			"pctLoss": "0%"
 		}
 	},
 	"request": {
 		"query": "www.somesite.com",
 		"timeout": "2",
 		"retry": "3",
 		"version": "v4"
 	}
 }, {
 	"response": {
 		"status": "success",
 		"result": {
 			"target": "www.someothersite.com",
 			"avgRtt": "4.811",
 			"maxRtt": "7.294",
 			"minRtt": "0.915",
 			"pctTransmitted": "3",
 			"pctReceived": "3",
 			"pctLoss": "0%"
 		}
 	},
 	"request": {
 		"query": "www.someothersite.com",
 		"timeout": "2",
 		"retry": "3",
 		"version": "v4"
 	}
 }, {
 	"response": {
 		"status": "success",
 		"result": {
 			"target": "www.someothersite.com",
 			"avgRtt": "4.781",
 			"maxRtt": "8.362",
 			"minRtt": "1.465",
 			"pctTransmitted": "3",
 			"pctReceived": "3",
 			"pctLoss": "0%"
 		}
 	},
 	"request": {
 		"query": "www.someothersite.com",
 		"timeout": "2",
 		"retry": "3",
 		"version": "v6"
 	}
 }]
```

### CODE REVIEW

**Comment by t1st3** [comment]
Hi @prernarana , thanks a lot for these changes; this PR is awesome! I'm going to review these today or tomorrow.

**Comment by t1st3** [comment]
@prernarana these changes are definitely going to land in the project; that's sure! But I'd like to add some tests for these new features and update the README consequently. Do you feel you could add more commits with these?

**Comment by prernarana** [comment]
@t1st3 Thanks!! I will update the README for sure, but I have never written test cases earlier. Can you please take care of the test cases?

**Comment by t1st3** [comment]
@prernarana that's great, thank you very much again!
Fair enough for the tests, I'm going to merge the PR as is, and I'll write some tests asap. Once I'm done with these tests, everything will be published to NPM with a new tag.

**Comment by t1st3** [comment]
Just published these changes in version 0.4.0.

**Comment by prernarana** [comment]
Thanks!! :)

**Pull request merged**
