### PR TITLE
Added iOS support

### PR DESCRIPTION
**Pull request by prernarana**

### CODE REVIEW

**Comment by t1st3** [comment]
Wow, thank you for this PR @prernarana. I'll start reviewing soon (probably today), but the review may take a while since I don't have any iPhone/iPad nor any Mac computer at the moment.

**Comment by qkdreyer** [comment]
Any updates ?

**Comment by t1st3** [comment]
@qkdreyer @prernarana 

Sorry, I completely forgot about this one, although, even after nearly 1 year, I still don't have any iOS device to test these changes.
I would merge this if I could get proof that:
* this runs normally on an iOS device
* or better: this passes the test suite on an iOS device

again, sorry for the delay

**Comment by crlang44** [comment]
@prernarana How are you using the plugin? In my javascript I get the error: 
```
ERROR in ./~/cordova-plugin-ping/www/ping.js
Module not found: Error: Can't resolve 'cordova' in 'C:\Users\clang\Desktop\hybrid-9514\node_modules\cordova-plugin-ping\www'
 @ ./~/cordova-plugin-ping/www/ping.js 4:12-30
 @ ./src/app/login/login.component.ts
 @ ./src/app/login/index.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts

ERROR in ./~/cordova-plugin-ping/www/ping.js
Module not found: Error: Can't resolve 'cordova/utils' in 'C:\Users\clang\Desktop\hybrid-9514\node_modules\cordova-plugin-ping\www'
 @ ./~/cordova-plugin-ping/www/ping.js 2:12-36
 @ ./src/app/login/login.component.ts
 @ ./src/app/login/index.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts

ERROR in ./~/cordova-plugin-ping/www/ping.js
Module not found: Error: Can't resolve 'cordova/exec' in 'C:\Users\clang\Desktop\hybrid-9514\node_modules\cordova-plugin-ping\www'
 @ ./~/cordova-plugin-ping/www/ping.js 3:9-32
 @ ./src/app/login/login.component.ts
 @ ./src/app/login/index.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
```
I have an angular 4 project and I am importing it into one of my components with:

`import { Ping } from 'cordova-plugin-ping/www/ping';`

Any comment would be appreciated.

Thanks

**Comment by crlang44** [comment]
I can confirm that it works for ios. I ended up just using @prernarana's repo since I need ios support. I don't know how to show this works but I can describe how I use it. For my app I allow the user to enter a hostname or ip address which will be their server that has a copy of our api server running on it. I use the ping plugin to check that the user-specified host can be reached before trying to make a call to one of the api endpoints, which would normally throw an error by the mobile browser that can't be caught or handled in javascript.

**Comment by cdeckard** [comment]
HI, what is the status of this?  I tried installing it directly, but cordova installed it as cordova-plugin-networkinterface for some reason.  trying to add it manually didn't work, either.

It *appears* pretty simple -- any particular hold-up on merging this?

**Comment by ZaLiTHkA** [comment]
has anyone got this to work on iOS 13? the comment by @crlang44 was before 13 was released..

I've added this to a simple Ionic 4 demo project, works perfectly on Android, but on iOS the app UI doesn't even load, which makes me think there's some initialisation issue here.

quick note: I'm on a Windows machine, so I have to build the app in Ionic AppFlow... I have no way to run it "locally" on iOS and see the debug output.

**edit:** I just fired up my test project on a really old (mid-2011) Mac Mini, which can't run the latest Xcode, but I can still build for iOS 12 and run in the simulator (which takes almost 10 minutes to launch, but anyways)..

looks like it works inside the simulator on iOS 12.1, so it looks like there's an issue with iOS 13 specifically here.

I have to go off to our company year-end function now, so I'll only be able to get back to this one on Monday again.

**Comment by cdeckard** [comment]
Here are my notes for getting this to run under iOS:



Oddly, this installs it as cordova-plugin-networkinterface (incorrect id tag in plugin.xml).  Instead, install the android-only plugin, then manually copy files over for iOS.  Use
cordova plugin add https://github.com/t1st3/cordova-plugin-ping.git
 

- install plugin using above command
- Manually copy the iOS files to the src directory in the plugin directory (I just copied them from the repo).
- also copy the <platform name="ios"> section in plugin.xml
- can also add "ios" to platforms tag in package.json, but i'm not sure this is required.
- create a directory in <PROJ_ROOT>/platforms/ios/Touchsmart/plugins/cordova-plugin-ping
- copy files from plrugin src ios to above directory
- add files to plugins folder in xcode
- Finally, To get this working, I had to manually add the following to config.xml in xcode (note, this was the config.xml under "staging=" folder):

 ```
<feature name="Ping">
   <param name="ios-package" value="CDVPing" />
 </feature>
```
adding this to plugin.xml should add it here automatically, but it didn't seem to work.

**Comment by ZaLiTHkA** [comment]
thanks for the tips, since I have no Mac machines here at home, I'll give that a go on Tuesday when I'm back at work (Monday is a public holiday).

**Pull request merged**
